# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
version: 2

builds:
  - id: rx
    binary: rx
    main: ./cli/rx

    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      -  "-s -w -X 'github.com/equinor/radix-cli/cmd.Version={{ .Version }}'"

dockers_v2:
  - dockerfile: Dockerfile.goreleaser
    images:
      - ghcr.io/equinor/radix/rx
    tags:
      - latest
      - "{{ .Version }}"
    labels:
      "org.opencontainers.image.description": "Radix CLI"
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.licenses": "MIT"
      "org.opencontainers.image.name": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "{{.GitURL}}"
      "org.opencontainers.image.url": "{{.GitURL}}"
    ids:
      - rx
    platforms:
      - linux/amd64
      - linux/arm64

archives:
  - name_template: >-
      {{- .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ .Tag }}-next"

changelog:
  disable: true
