// Code generated by go-swagger; DO NOT EDIT.

package job

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewRestartJobParams creates a new RestartJobParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewRestartJobParams() *RestartJobParams {
	return &RestartJobParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewRestartJobParamsWithTimeout creates a new RestartJobParams object
// with the ability to set a timeout on a request.
func NewRestartJobParamsWithTimeout(timeout time.Duration) *RestartJobParams {
	return &RestartJobParams{
		timeout: timeout,
	}
}

// NewRestartJobParamsWithContext creates a new RestartJobParams object
// with the ability to set a context for a request.
func NewRestartJobParamsWithContext(ctx context.Context) *RestartJobParams {
	return &RestartJobParams{
		Context: ctx,
	}
}

// NewRestartJobParamsWithHTTPClient creates a new RestartJobParams object
// with the ability to set a custom HTTPClient for a request.
func NewRestartJobParamsWithHTTPClient(client *http.Client) *RestartJobParams {
	return &RestartJobParams{
		HTTPClient: client,
	}
}

/*
RestartJobParams contains all the parameters to send to the API endpoint

	for the restart job operation.

	Typically these are written to a http.Request.
*/
type RestartJobParams struct {

	/* ImpersonateGroup.

	   Works only with custom setup of cluster. Allow impersonation of a comma-seperated list of test groups (Required if Impersonate-User is set)
	*/
	ImpersonateGroup *string

	/* ImpersonateUser.

	   Works only with custom setup of cluster. Allow impersonation of test users (Required if Impersonate-Group is set)
	*/
	ImpersonateUser *string

	/* AppName.

	   Name of application
	*/
	AppName string

	/* EnvName.

	   Name of environment
	*/
	EnvName string

	/* JobComponentName.

	   Name of job-component
	*/
	JobComponentName string

	/* JobName.

	   Name of job
	*/
	JobName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the restart job params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RestartJobParams) WithDefaults() *RestartJobParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the restart job params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RestartJobParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the restart job params
func (o *RestartJobParams) WithTimeout(timeout time.Duration) *RestartJobParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the restart job params
func (o *RestartJobParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the restart job params
func (o *RestartJobParams) WithContext(ctx context.Context) *RestartJobParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the restart job params
func (o *RestartJobParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the restart job params
func (o *RestartJobParams) WithHTTPClient(client *http.Client) *RestartJobParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the restart job params
func (o *RestartJobParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithImpersonateGroup adds the impersonateGroup to the restart job params
func (o *RestartJobParams) WithImpersonateGroup(impersonateGroup *string) *RestartJobParams {
	o.SetImpersonateGroup(impersonateGroup)
	return o
}

// SetImpersonateGroup adds the impersonateGroup to the restart job params
func (o *RestartJobParams) SetImpersonateGroup(impersonateGroup *string) {
	o.ImpersonateGroup = impersonateGroup
}

// WithImpersonateUser adds the impersonateUser to the restart job params
func (o *RestartJobParams) WithImpersonateUser(impersonateUser *string) *RestartJobParams {
	o.SetImpersonateUser(impersonateUser)
	return o
}

// SetImpersonateUser adds the impersonateUser to the restart job params
func (o *RestartJobParams) SetImpersonateUser(impersonateUser *string) {
	o.ImpersonateUser = impersonateUser
}

// WithAppName adds the appName to the restart job params
func (o *RestartJobParams) WithAppName(appName string) *RestartJobParams {
	o.SetAppName(appName)
	return o
}

// SetAppName adds the appName to the restart job params
func (o *RestartJobParams) SetAppName(appName string) {
	o.AppName = appName
}

// WithEnvName adds the envName to the restart job params
func (o *RestartJobParams) WithEnvName(envName string) *RestartJobParams {
	o.SetEnvName(envName)
	return o
}

// SetEnvName adds the envName to the restart job params
func (o *RestartJobParams) SetEnvName(envName string) {
	o.EnvName = envName
}

// WithJobComponentName adds the jobComponentName to the restart job params
func (o *RestartJobParams) WithJobComponentName(jobComponentName string) *RestartJobParams {
	o.SetJobComponentName(jobComponentName)
	return o
}

// SetJobComponentName adds the jobComponentName to the restart job params
func (o *RestartJobParams) SetJobComponentName(jobComponentName string) {
	o.JobComponentName = jobComponentName
}

// WithJobName adds the jobName to the restart job params
func (o *RestartJobParams) WithJobName(jobName string) *RestartJobParams {
	o.SetJobName(jobName)
	return o
}

// SetJobName adds the jobName to the restart job params
func (o *RestartJobParams) SetJobName(jobName string) {
	o.JobName = jobName
}

// WriteToRequest writes these params to a swagger request
func (o *RestartJobParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.ImpersonateGroup != nil {

		// header param Impersonate-Group
		if err := r.SetHeaderParam("Impersonate-Group", *o.ImpersonateGroup); err != nil {
			return err
		}
	}

	if o.ImpersonateUser != nil {

		// header param Impersonate-User
		if err := r.SetHeaderParam("Impersonate-User", *o.ImpersonateUser); err != nil {
			return err
		}
	}

	// path param appName
	if err := r.SetPathParam("appName", o.AppName); err != nil {
		return err
	}

	// path param envName
	if err := r.SetPathParam("envName", o.EnvName); err != nil {
		return err
	}

	// path param jobComponentName
	if err := r.SetPathParam("jobComponentName", o.JobComponentName); err != nil {
		return err
	}

	// path param jobName
	if err := r.SetPathParam("jobName", o.JobName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
