// Code generated by go-swagger; DO NOT EDIT.

package job

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewStopJobParams creates a new StopJobParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewStopJobParams() *StopJobParams {
	return &StopJobParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewStopJobParamsWithTimeout creates a new StopJobParams object
// with the ability to set a timeout on a request.
func NewStopJobParamsWithTimeout(timeout time.Duration) *StopJobParams {
	return &StopJobParams{
		timeout: timeout,
	}
}

// NewStopJobParamsWithContext creates a new StopJobParams object
// with the ability to set a context for a request.
func NewStopJobParamsWithContext(ctx context.Context) *StopJobParams {
	return &StopJobParams{
		Context: ctx,
	}
}

// NewStopJobParamsWithHTTPClient creates a new StopJobParams object
// with the ability to set a custom HTTPClient for a request.
func NewStopJobParamsWithHTTPClient(client *http.Client) *StopJobParams {
	return &StopJobParams{
		HTTPClient: client,
	}
}

/*
StopJobParams contains all the parameters to send to the API endpoint

	for the stop job operation.

	Typically these are written to a http.Request.
*/
type StopJobParams struct {

	/* ImpersonateGroup.

	   Works only with custom setup of cluster. Allow impersonation of a comma-seperated list of test groups (Required if Impersonate-User is set)
	*/
	ImpersonateGroup *string

	/* ImpersonateUser.

	   Works only with custom setup of cluster. Allow impersonation of test users (Required if Impersonate-Group is set)
	*/
	ImpersonateUser *string

	/* AppName.

	   Name of application
	*/
	AppName string

	/* EnvName.

	   Name of environment
	*/
	EnvName string

	/* JobComponentName.

	   Name of job-component
	*/
	JobComponentName string

	/* JobName.

	   Name of job
	*/
	JobName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the stop job params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *StopJobParams) WithDefaults() *StopJobParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the stop job params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *StopJobParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the stop job params
func (o *StopJobParams) WithTimeout(timeout time.Duration) *StopJobParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the stop job params
func (o *StopJobParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the stop job params
func (o *StopJobParams) WithContext(ctx context.Context) *StopJobParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the stop job params
func (o *StopJobParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the stop job params
func (o *StopJobParams) WithHTTPClient(client *http.Client) *StopJobParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the stop job params
func (o *StopJobParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithImpersonateGroup adds the impersonateGroup to the stop job params
func (o *StopJobParams) WithImpersonateGroup(impersonateGroup *string) *StopJobParams {
	o.SetImpersonateGroup(impersonateGroup)
	return o
}

// SetImpersonateGroup adds the impersonateGroup to the stop job params
func (o *StopJobParams) SetImpersonateGroup(impersonateGroup *string) {
	o.ImpersonateGroup = impersonateGroup
}

// WithImpersonateUser adds the impersonateUser to the stop job params
func (o *StopJobParams) WithImpersonateUser(impersonateUser *string) *StopJobParams {
	o.SetImpersonateUser(impersonateUser)
	return o
}

// SetImpersonateUser adds the impersonateUser to the stop job params
func (o *StopJobParams) SetImpersonateUser(impersonateUser *string) {
	o.ImpersonateUser = impersonateUser
}

// WithAppName adds the appName to the stop job params
func (o *StopJobParams) WithAppName(appName string) *StopJobParams {
	o.SetAppName(appName)
	return o
}

// SetAppName adds the appName to the stop job params
func (o *StopJobParams) SetAppName(appName string) {
	o.AppName = appName
}

// WithEnvName adds the envName to the stop job params
func (o *StopJobParams) WithEnvName(envName string) *StopJobParams {
	o.SetEnvName(envName)
	return o
}

// SetEnvName adds the envName to the stop job params
func (o *StopJobParams) SetEnvName(envName string) {
	o.EnvName = envName
}

// WithJobComponentName adds the jobComponentName to the stop job params
func (o *StopJobParams) WithJobComponentName(jobComponentName string) *StopJobParams {
	o.SetJobComponentName(jobComponentName)
	return o
}

// SetJobComponentName adds the jobComponentName to the stop job params
func (o *StopJobParams) SetJobComponentName(jobComponentName string) {
	o.JobComponentName = jobComponentName
}

// WithJobName adds the jobName to the stop job params
func (o *StopJobParams) WithJobName(jobName string) *StopJobParams {
	o.SetJobName(jobName)
	return o
}

// SetJobName adds the jobName to the stop job params
func (o *StopJobParams) SetJobName(jobName string) {
	o.JobName = jobName
}

// WriteToRequest writes these params to a swagger request
func (o *StopJobParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.ImpersonateGroup != nil {

		// header param Impersonate-Group
		if err := r.SetHeaderParam("Impersonate-Group", *o.ImpersonateGroup); err != nil {
			return err
		}
	}

	if o.ImpersonateUser != nil {

		// header param Impersonate-User
		if err := r.SetHeaderParam("Impersonate-User", *o.ImpersonateUser); err != nil {
			return err
		}
	}

	// path param appName
	if err := r.SetPathParam("appName", o.AppName); err != nil {
		return err
	}

	// path param envName
	if err := r.SetPathParam("envName", o.EnvName); err != nil {
		return err
	}

	// path param jobComponentName
	if err := r.SetPathParam("jobComponentName", o.JobComponentName); err != nil {
		return err
	}

	// path param jobName
	if err := r.SetPathParam("jobName", o.JobName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
