package flagnames

const (
	AcknowledgeWarnings = "acknowledge-warnings"
	AdminADGroups       = "ad-groups"
	Alias               = "alias"
	ApiEnvironment      = "api-environment"
	Application         = "application"
	AwaitReconcile      = "await-reconcile"
	Branch              = "branch"
	Certificate         = "certificate"
	CertificateFromFile = "certificate-from-file"
	Cluster             = "cluster"
	CommitID            = "commitID"
	Component           = "component"
	ConfigurationItem   = "configuration-item"
	ConfigBranch        = "config-branch"
	ConfigFile          = "config-file"
	Context             = "context"
	Deployment          = "deployment"
	Environment         = "environment"
	Follow              = "follow"
	FromConfig          = "from-config"
	FromEnvironment     = "from-environment"
	ImageTagName        = "image-tag-name"
	Job                 = "job"
	Previous            = "previous"
	Print               = "print"
	PrivateKey          = "private-key"
	PrivateKeyFromFile  = "private-key-from-file"
	ReaderADGroups      = "reader-ad-groups"
	Replicas            = "replicas"
	Repository          = "repository"
	Secret              = "secret"
	SharedSecret        = "shared-secret"
	Since               = "since"
	SkipValidation      = "skip-validation"
	ToEnvironment       = "to-environment"
	TokenEnvironment    = "token-environment"
	TokenStdin          = "token-stdin"
	UseActiveDeployment = "use-active-deployment"
	UseDeviceCode       = "use-device-code"
	User                = "user"
	Variable            = "variable"
	Verbose             = "verbose"
	Value               = "value"
)
