// Code generated by go-swagger; DO NOT EDIT.

package component

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewEnvVarsParams creates a new EnvVarsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewEnvVarsParams() *EnvVarsParams {
	return &EnvVarsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewEnvVarsParamsWithTimeout creates a new EnvVarsParams object
// with the ability to set a timeout on a request.
func NewEnvVarsParamsWithTimeout(timeout time.Duration) *EnvVarsParams {
	return &EnvVarsParams{
		timeout: timeout,
	}
}

// NewEnvVarsParamsWithContext creates a new EnvVarsParams object
// with the ability to set a context for a request.
func NewEnvVarsParamsWithContext(ctx context.Context) *EnvVarsParams {
	return &EnvVarsParams{
		Context: ctx,
	}
}

// NewEnvVarsParamsWithHTTPClient creates a new EnvVarsParams object
// with the ability to set a custom HTTPClient for a request.
func NewEnvVarsParamsWithHTTPClient(client *http.Client) *EnvVarsParams {
	return &EnvVarsParams{
		HTTPClient: client,
	}
}

/*
EnvVarsParams contains all the parameters to send to the API endpoint

	for the env vars operation.

	Typically these are written to a http.Request.
*/
type EnvVarsParams struct {

	/* ImpersonateGroup.

	   Works only with custom setup of cluster. Allow impersonation of a comma-seperated list of test groups (Required if Impersonate-User is set)
	*/
	ImpersonateGroup *string

	/* ImpersonateUser.

	   Works only with custom setup of cluster. Allow impersonation of test users (Required if Impersonate-Group is set)
	*/
	ImpersonateUser *string

	/* AppName.

	   Name of application
	*/
	AppName string

	/* ComponentName.

	   Name of component
	*/
	ComponentName string

	/* EnvName.

	   Name of environment
	*/
	EnvName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the env vars params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *EnvVarsParams) WithDefaults() *EnvVarsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the env vars params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *EnvVarsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the env vars params
func (o *EnvVarsParams) WithTimeout(timeout time.Duration) *EnvVarsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the env vars params
func (o *EnvVarsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the env vars params
func (o *EnvVarsParams) WithContext(ctx context.Context) *EnvVarsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the env vars params
func (o *EnvVarsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the env vars params
func (o *EnvVarsParams) WithHTTPClient(client *http.Client) *EnvVarsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the env vars params
func (o *EnvVarsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithImpersonateGroup adds the impersonateGroup to the env vars params
func (o *EnvVarsParams) WithImpersonateGroup(impersonateGroup *string) *EnvVarsParams {
	o.SetImpersonateGroup(impersonateGroup)
	return o
}

// SetImpersonateGroup adds the impersonateGroup to the env vars params
func (o *EnvVarsParams) SetImpersonateGroup(impersonateGroup *string) {
	o.ImpersonateGroup = impersonateGroup
}

// WithImpersonateUser adds the impersonateUser to the env vars params
func (o *EnvVarsParams) WithImpersonateUser(impersonateUser *string) *EnvVarsParams {
	o.SetImpersonateUser(impersonateUser)
	return o
}

// SetImpersonateUser adds the impersonateUser to the env vars params
func (o *EnvVarsParams) SetImpersonateUser(impersonateUser *string) {
	o.ImpersonateUser = impersonateUser
}

// WithAppName adds the appName to the env vars params
func (o *EnvVarsParams) WithAppName(appName string) *EnvVarsParams {
	o.SetAppName(appName)
	return o
}

// SetAppName adds the appName to the env vars params
func (o *EnvVarsParams) SetAppName(appName string) {
	o.AppName = appName
}

// WithComponentName adds the componentName to the env vars params
func (o *EnvVarsParams) WithComponentName(componentName string) *EnvVarsParams {
	o.SetComponentName(componentName)
	return o
}

// SetComponentName adds the componentName to the env vars params
func (o *EnvVarsParams) SetComponentName(componentName string) {
	o.ComponentName = componentName
}

// WithEnvName adds the envName to the env vars params
func (o *EnvVarsParams) WithEnvName(envName string) *EnvVarsParams {
	o.SetEnvName(envName)
	return o
}

// SetEnvName adds the envName to the env vars params
func (o *EnvVarsParams) SetEnvName(envName string) {
	o.EnvName = envName
}

// WriteToRequest writes these params to a swagger request
func (o *EnvVarsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.ImpersonateGroup != nil {

		// header param Impersonate-Group
		if err := r.SetHeaderParam("Impersonate-Group", *o.ImpersonateGroup); err != nil {
			return err
		}
	}

	if o.ImpersonateUser != nil {

		// header param Impersonate-User
		if err := r.SetHeaderParam("Impersonate-User", *o.ImpersonateUser); err != nil {
			return err
		}
	}

	// path param appName
	if err := r.SetPathParam("appName", o.AppName); err != nil {
		return err
	}

	// path param componentName
	if err := r.SetPathParam("componentName", o.ComponentName); err != nil {
		return err
	}

	// path param envName
	if err := r.SetPathParam("envName", o.EnvName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
