// Code generated by go-swagger; DO NOT EDIT.

package component

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/equinor/radix-cli/generated-client/models"
)

// NewUpdateComponentExternalDNSTLSParams creates a new UpdateComponentExternalDNSTLSParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateComponentExternalDNSTLSParams() *UpdateComponentExternalDNSTLSParams {
	return &UpdateComponentExternalDNSTLSParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateComponentExternalDNSTLSParamsWithTimeout creates a new UpdateComponentExternalDNSTLSParams object
// with the ability to set a timeout on a request.
func NewUpdateComponentExternalDNSTLSParamsWithTimeout(timeout time.Duration) *UpdateComponentExternalDNSTLSParams {
	return &UpdateComponentExternalDNSTLSParams{
		timeout: timeout,
	}
}

// NewUpdateComponentExternalDNSTLSParamsWithContext creates a new UpdateComponentExternalDNSTLSParams object
// with the ability to set a context for a request.
func NewUpdateComponentExternalDNSTLSParamsWithContext(ctx context.Context) *UpdateComponentExternalDNSTLSParams {
	return &UpdateComponentExternalDNSTLSParams{
		Context: ctx,
	}
}

// NewUpdateComponentExternalDNSTLSParamsWithHTTPClient creates a new UpdateComponentExternalDNSTLSParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateComponentExternalDNSTLSParamsWithHTTPClient(client *http.Client) *UpdateComponentExternalDNSTLSParams {
	return &UpdateComponentExternalDNSTLSParams{
		HTTPClient: client,
	}
}

/*
UpdateComponentExternalDNSTLSParams contains all the parameters to send to the API endpoint

	for the update component external Dns Tls operation.

	Typically these are written to a http.Request.
*/
type UpdateComponentExternalDNSTLSParams struct {

	/* ImpersonateGroup.

	   Works only with custom setup of cluster. Allow impersonation of a comma-seperated list of test groups (Required if Impersonate-User is set)
	*/
	ImpersonateGroup *string

	/* ImpersonateUser.

	   Works only with custom setup of cluster. Allow impersonation of test users (Required if Impersonate-Group is set)
	*/
	ImpersonateUser *string

	/* AppName.

	   Name of application
	*/
	AppName string

	/* ComponentName.

	   secret component of Radix application
	*/
	ComponentName string

	/* EnvName.

	   secret of Radix application
	*/
	EnvName string

	/* Fqdn.

	   FQDN to be updated
	*/
	Fqdn string

	/* TLSData.

	   New TLS private key and certificate
	*/
	TLSData *models.UpdateExternalDNSTLSRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update component external Dns Tls params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateComponentExternalDNSTLSParams) WithDefaults() *UpdateComponentExternalDNSTLSParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update component external Dns Tls params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateComponentExternalDNSTLSParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update component external Dns Tls params
func (o *UpdateComponentExternalDNSTLSParams) WithTimeout(timeout time.Duration) *UpdateComponentExternalDNSTLSParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update component external Dns Tls params
func (o *UpdateComponentExternalDNSTLSParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update component external Dns Tls params
func (o *UpdateComponentExternalDNSTLSParams) WithContext(ctx context.Context) *UpdateComponentExternalDNSTLSParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update component external Dns Tls params
func (o *UpdateComponentExternalDNSTLSParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update component external Dns Tls params
func (o *UpdateComponentExternalDNSTLSParams) WithHTTPClient(client *http.Client) *UpdateComponentExternalDNSTLSParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update component external Dns Tls params
func (o *UpdateComponentExternalDNSTLSParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithImpersonateGroup adds the impersonateGroup to the update component external Dns Tls params
func (o *UpdateComponentExternalDNSTLSParams) WithImpersonateGroup(impersonateGroup *string) *UpdateComponentExternalDNSTLSParams {
	o.SetImpersonateGroup(impersonateGroup)
	return o
}

// SetImpersonateGroup adds the impersonateGroup to the update component external Dns Tls params
func (o *UpdateComponentExternalDNSTLSParams) SetImpersonateGroup(impersonateGroup *string) {
	o.ImpersonateGroup = impersonateGroup
}

// WithImpersonateUser adds the impersonateUser to the update component external Dns Tls params
func (o *UpdateComponentExternalDNSTLSParams) WithImpersonateUser(impersonateUser *string) *UpdateComponentExternalDNSTLSParams {
	o.SetImpersonateUser(impersonateUser)
	return o
}

// SetImpersonateUser adds the impersonateUser to the update component external Dns Tls params
func (o *UpdateComponentExternalDNSTLSParams) SetImpersonateUser(impersonateUser *string) {
	o.ImpersonateUser = impersonateUser
}

// WithAppName adds the appName to the update component external Dns Tls params
func (o *UpdateComponentExternalDNSTLSParams) WithAppName(appName string) *UpdateComponentExternalDNSTLSParams {
	o.SetAppName(appName)
	return o
}

// SetAppName adds the appName to the update component external Dns Tls params
func (o *UpdateComponentExternalDNSTLSParams) SetAppName(appName string) {
	o.AppName = appName
}

// WithComponentName adds the componentName to the update component external Dns Tls params
func (o *UpdateComponentExternalDNSTLSParams) WithComponentName(componentName string) *UpdateComponentExternalDNSTLSParams {
	o.SetComponentName(componentName)
	return o
}

// SetComponentName adds the componentName to the update component external Dns Tls params
func (o *UpdateComponentExternalDNSTLSParams) SetComponentName(componentName string) {
	o.ComponentName = componentName
}

// WithEnvName adds the envName to the update component external Dns Tls params
func (o *UpdateComponentExternalDNSTLSParams) WithEnvName(envName string) *UpdateComponentExternalDNSTLSParams {
	o.SetEnvName(envName)
	return o
}

// SetEnvName adds the envName to the update component external Dns Tls params
func (o *UpdateComponentExternalDNSTLSParams) SetEnvName(envName string) {
	o.EnvName = envName
}

// WithFqdn adds the fqdn to the update component external Dns Tls params
func (o *UpdateComponentExternalDNSTLSParams) WithFqdn(fqdn string) *UpdateComponentExternalDNSTLSParams {
	o.SetFqdn(fqdn)
	return o
}

// SetFqdn adds the fqdn to the update component external Dns Tls params
func (o *UpdateComponentExternalDNSTLSParams) SetFqdn(fqdn string) {
	o.Fqdn = fqdn
}

// WithTLSData adds the tLSData to the update component external Dns Tls params
func (o *UpdateComponentExternalDNSTLSParams) WithTLSData(tLSData *models.UpdateExternalDNSTLSRequest) *UpdateComponentExternalDNSTLSParams {
	o.SetTLSData(tLSData)
	return o
}

// SetTLSData adds the tlsData to the update component external Dns Tls params
func (o *UpdateComponentExternalDNSTLSParams) SetTLSData(tLSData *models.UpdateExternalDNSTLSRequest) {
	o.TLSData = tLSData
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateComponentExternalDNSTLSParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.ImpersonateGroup != nil {

		// header param Impersonate-Group
		if err := r.SetHeaderParam("Impersonate-Group", *o.ImpersonateGroup); err != nil {
			return err
		}
	}

	if o.ImpersonateUser != nil {

		// header param Impersonate-User
		if err := r.SetHeaderParam("Impersonate-User", *o.ImpersonateUser); err != nil {
			return err
		}
	}

	// path param appName
	if err := r.SetPathParam("appName", o.AppName); err != nil {
		return err
	}

	// path param componentName
	if err := r.SetPathParam("componentName", o.ComponentName); err != nil {
		return err
	}

	// path param envName
	if err := r.SetPathParam("envName", o.EnvName); err != nil {
		return err
	}

	// path param fqdn
	if err := r.SetPathParam("fqdn", o.Fqdn); err != nil {
		return err
	}
	if o.TLSData != nil {
		if err := r.SetBodyParam(o.TLSData); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
