// Code generated by go-swagger; DO NOT EDIT.

package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/equinor/radix-cli/generated-client/client/application"
	"github.com/equinor/radix-cli/generated-client/client/buildstatus"
	"github.com/equinor/radix-cli/generated-client/client/component"
	"github.com/equinor/radix-cli/generated-client/client/deployment"
	"github.com/equinor/radix-cli/generated-client/client/environment"
	"github.com/equinor/radix-cli/generated-client/client/job"
	"github.com/equinor/radix-cli/generated-client/client/pipeline_job"
	"github.com/equinor/radix-cli/generated-client/client/platform"
)

// Default radixapi HTTP client.
var Default = NewHTTPClient(nil)

const (
	// DefaultHost is the default Host
	// found in Meta (info) section of spec file
	DefaultHost string = "localhost"
	// DefaultBasePath is the default BasePath
	// found in Meta (info) section of spec file
	DefaultBasePath string = "/api/v1"
)

// DefaultSchemes are the default schemes found in Meta (info) section of spec file
var DefaultSchemes = []string{"http", "https"}

// NewHTTPClient creates a new radixapi HTTP client.
func NewHTTPClient(formats strfmt.Registry) *Radixapi {
	return NewHTTPClientWithConfig(formats, nil)
}

// NewHTTPClientWithConfig creates a new radixapi HTTP client,
// using a customizable transport config.
func NewHTTPClientWithConfig(formats strfmt.Registry, cfg *TransportConfig) *Radixapi {
	// ensure nullable parameters have default
	if cfg == nil {
		cfg = DefaultTransportConfig()
	}

	// create transport and client
	transport := httptransport.New(cfg.Host, cfg.BasePath, cfg.Schemes)
	return New(transport, formats)
}

// New creates a new radixapi client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Radixapi {
	// ensure nullable parameters have default
	if formats == nil {
		formats = strfmt.Default
	}

	cli := new(Radixapi)
	cli.Transport = transport
	cli.Application = application.New(transport, formats)
	cli.Buildstatus = buildstatus.New(transport, formats)
	cli.Component = component.New(transport, formats)
	cli.Deployment = deployment.New(transport, formats)
	cli.Environment = environment.New(transport, formats)
	cli.Job = job.New(transport, formats)
	cli.PipelineJob = pipeline_job.New(transport, formats)
	cli.Platform = platform.New(transport, formats)
	return cli
}

// DefaultTransportConfig creates a TransportConfig with the
// default settings taken from the meta section of the spec file.
func DefaultTransportConfig() *TransportConfig {
	return &TransportConfig{
		Host:     DefaultHost,
		BasePath: DefaultBasePath,
		Schemes:  DefaultSchemes,
	}
}

// TransportConfig contains the transport related info,
// found in the meta section of the spec file.
type TransportConfig struct {
	Host     string
	BasePath string
	Schemes  []string
}

// WithHost overrides the default host,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithHost(host string) *TransportConfig {
	cfg.Host = host
	return cfg
}

// WithBasePath overrides the default basePath,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithBasePath(basePath string) *TransportConfig {
	cfg.BasePath = basePath
	return cfg
}

// WithSchemes overrides the default schemes,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithSchemes(schemes []string) *TransportConfig {
	cfg.Schemes = schemes
	return cfg
}

// Radixapi is a client for radixapi
type Radixapi struct {
	Application application.ClientService

	Buildstatus buildstatus.ClientService

	Component component.ClientService

	Deployment deployment.ClientService

	Environment environment.ClientService

	Job job.ClientService

	PipelineJob pipeline_job.ClientService

	Platform platform.ClientService

	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *Radixapi) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport
	c.Application.SetTransport(transport)
	c.Buildstatus.SetTransport(transport)
	c.Component.SetTransport(transport)
	c.Deployment.SetTransport(transport)
	c.Environment.SetTransport(transport)
	c.Job.SetTransport(transport)
	c.PipelineJob.SetTransport(transport)
	c.Platform.SetTransport(transport)
}
