// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// HorizontalScalingSummary HorizontalScalingSummary describe the summary of horizontal scaling of a component
//
// swagger:model HorizontalScalingSummary
type HorizontalScalingSummary struct {

	// Component current average CPU utilization over all pods, represented as a percentage of requested CPU
	// Example: 70
	CurrentCPUUtilizationPercentage int32 `json:"currentCPUUtilizationPercentage,omitempty"`

	// Component current average memory utilization over all pods, represented as a percentage of requested memory
	// Example: 80
	CurrentMemoryUtilizationPercentage int32 `json:"currentMemoryUtilizationPercentage,omitempty"`

	// Component maximum replicas. From radixconfig.yaml
	// Example: 5
	MaxReplicas int32 `json:"maxReplicas,omitempty"`

	// Component minimum replicas. From radixconfig.yaml
	// Example: 2
	MinReplicas int32 `json:"minReplicas,omitempty"`

	// Component target average CPU utilization over all pods
	// Example: 80
	TargetCPUUtilizationPercentage int32 `json:"targetCPUUtilizationPercentage,omitempty"`

	// Component target average memory utilization over all pods
	// Example: 80
	TargetMemoryUtilizationPercentage int32 `json:"targetMemoryUtilizationPercentage,omitempty"`
}

// Validate validates this horizontal scaling summary
func (m *HorizontalScalingSummary) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this horizontal scaling summary based on context it is used
func (m *HorizontalScalingSummary) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *HorizontalScalingSummary) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HorizontalScalingSummary) UnmarshalBinary(b []byte) error {
	var res HorizontalScalingSummary
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
