// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Ingress Ingress describes ingress configuration for a component
//
// swagger:model Ingress
type Ingress struct {

	// public
	Public *IngressPublic `json:"public,omitempty"`
}

// Validate validates this ingress
func (m *Ingress) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePublic(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Ingress) validatePublic(formats strfmt.Registry) error {
	if swag.IsZero(m.Public) { // not required
		return nil
	}

	if m.Public != nil {
		if err := m.Public.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("public")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("public")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this ingress based on the context it is used
func (m *Ingress) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidatePublic(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Ingress) contextValidatePublic(ctx context.Context, formats strfmt.Registry) error {

	if m.Public != nil {

		if swag.IsZero(m.Public) { // not required
			return nil
		}

		if err := m.Public.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("public")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("public")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Ingress) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Ingress) UnmarshalBinary(b []byte) error {
	var res Ingress
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
