// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ObjectState ObjectState holds information about the state of objects involved in an event
//
// swagger:model ObjectState
type ObjectState struct {

	// pod
	Pod *PodState `json:"pod,omitempty"`
}

// Validate validates this object state
func (m *ObjectState) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePod(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ObjectState) validatePod(formats strfmt.Registry) error {
	if swag.IsZero(m.Pod) { // not required
		return nil
	}

	if m.Pod != nil {
		if err := m.Pod.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("pod")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("pod")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this object state based on the context it is used
func (m *ObjectState) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidatePod(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ObjectState) contextValidatePod(ctx context.Context, formats strfmt.Registry) error {

	if m.Pod != nil {

		if swag.IsZero(m.Pod) { // not required
			return nil
		}

		if err := m.Pod.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("pod")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("pod")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ObjectState) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ObjectState) UnmarshalBinary(b []byte) error {
	var res ObjectState
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
