// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PromotionParameters PromotionParameters describe environment to promote from and to
//
// swagger:model PromotionParameters
type PromotionParameters struct {

	// FromEnvironment the environment to promote from
	// Example: dev
	// Required: true
	FromEnvironment *string `json:"fromEnvironment"`

	// ToEnvironment the environment to promote to
	// Example: prod
	// Required: true
	ToEnvironment *string `json:"toEnvironment"`
}

// Validate validates this promotion parameters
func (m *PromotionParameters) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFromEnvironment(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateToEnvironment(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PromotionParameters) validateFromEnvironment(formats strfmt.Registry) error {

	if err := validate.Required("fromEnvironment", "body", m.FromEnvironment); err != nil {
		return err
	}

	return nil
}

func (m *PromotionParameters) validateToEnvironment(formats strfmt.Registry) error {

	if err := validate.Required("toEnvironment", "body", m.ToEnvironment); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this promotion parameters based on context it is used
func (m *PromotionParameters) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PromotionParameters) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PromotionParameters) UnmarshalBinary(b []byte) error {
	var res PromotionParameters
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
