// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Resources Resources Required for pods
//
// swagger:model Resources
type Resources struct {

	// CPU
	CPU string `json:"cpu,omitempty"`

	// memory
	Memory string `json:"memory,omitempty"`
}

// Validate validates this resources
func (m *Resources) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this resources based on context it is used
func (m *Resources) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Resources) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Resources) UnmarshalBinary(b []byte) error {
	var res Resources
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
