// Code generated by go-swagger; DO NOT EDIT.

package pipeline_job

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetPipelineJobStepLogsReader is a Reader for the GetPipelineJobStepLogs structure.
type GetPipelineJobStepLogsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPipelineJobStepLogsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetPipelineJobStepLogsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetPipelineJobStepLogsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetPipelineJobStepLogsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /applications/{appName}/jobs/{jobName}/logs/{stepName}] getPipelineJobStepLogs", response, response.Code())
	}
}

// NewGetPipelineJobStepLogsOK creates a GetPipelineJobStepLogsOK with default headers values
func NewGetPipelineJobStepLogsOK() *GetPipelineJobStepLogsOK {
	return &GetPipelineJobStepLogsOK{}
}

/*
GetPipelineJobStepLogsOK describes a response with status code 200, with default header values.

Job step log
*/
type GetPipelineJobStepLogsOK struct {
	Payload string
}

// IsSuccess returns true when this get pipeline job step logs o k response has a 2xx status code
func (o *GetPipelineJobStepLogsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get pipeline job step logs o k response has a 3xx status code
func (o *GetPipelineJobStepLogsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get pipeline job step logs o k response has a 4xx status code
func (o *GetPipelineJobStepLogsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get pipeline job step logs o k response has a 5xx status code
func (o *GetPipelineJobStepLogsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get pipeline job step logs o k response a status code equal to that given
func (o *GetPipelineJobStepLogsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get pipeline job step logs o k response
func (o *GetPipelineJobStepLogsOK) Code() int {
	return 200
}

func (o *GetPipelineJobStepLogsOK) Error() string {
	return fmt.Sprintf("[GET /applications/{appName}/jobs/{jobName}/logs/{stepName}][%d] getPipelineJobStepLogsOK  %+v", 200, o.Payload)
}

func (o *GetPipelineJobStepLogsOK) String() string {
	return fmt.Sprintf("[GET /applications/{appName}/jobs/{jobName}/logs/{stepName}][%d] getPipelineJobStepLogsOK  %+v", 200, o.Payload)
}

func (o *GetPipelineJobStepLogsOK) GetPayload() string {
	return o.Payload
}

func (o *GetPipelineJobStepLogsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetPipelineJobStepLogsUnauthorized creates a GetPipelineJobStepLogsUnauthorized with default headers values
func NewGetPipelineJobStepLogsUnauthorized() *GetPipelineJobStepLogsUnauthorized {
	return &GetPipelineJobStepLogsUnauthorized{}
}

/*
GetPipelineJobStepLogsUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetPipelineJobStepLogsUnauthorized struct {
}

// IsSuccess returns true when this get pipeline job step logs unauthorized response has a 2xx status code
func (o *GetPipelineJobStepLogsUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get pipeline job step logs unauthorized response has a 3xx status code
func (o *GetPipelineJobStepLogsUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get pipeline job step logs unauthorized response has a 4xx status code
func (o *GetPipelineJobStepLogsUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get pipeline job step logs unauthorized response has a 5xx status code
func (o *GetPipelineJobStepLogsUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get pipeline job step logs unauthorized response a status code equal to that given
func (o *GetPipelineJobStepLogsUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the get pipeline job step logs unauthorized response
func (o *GetPipelineJobStepLogsUnauthorized) Code() int {
	return 401
}

func (o *GetPipelineJobStepLogsUnauthorized) Error() string {
	return fmt.Sprintf("[GET /applications/{appName}/jobs/{jobName}/logs/{stepName}][%d] getPipelineJobStepLogsUnauthorized ", 401)
}

func (o *GetPipelineJobStepLogsUnauthorized) String() string {
	return fmt.Sprintf("[GET /applications/{appName}/jobs/{jobName}/logs/{stepName}][%d] getPipelineJobStepLogsUnauthorized ", 401)
}

func (o *GetPipelineJobStepLogsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetPipelineJobStepLogsNotFound creates a GetPipelineJobStepLogsNotFound with default headers values
func NewGetPipelineJobStepLogsNotFound() *GetPipelineJobStepLogsNotFound {
	return &GetPipelineJobStepLogsNotFound{}
}

/*
GetPipelineJobStepLogsNotFound describes a response with status code 404, with default header values.

Not found
*/
type GetPipelineJobStepLogsNotFound struct {
}

// IsSuccess returns true when this get pipeline job step logs not found response has a 2xx status code
func (o *GetPipelineJobStepLogsNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get pipeline job step logs not found response has a 3xx status code
func (o *GetPipelineJobStepLogsNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get pipeline job step logs not found response has a 4xx status code
func (o *GetPipelineJobStepLogsNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get pipeline job step logs not found response has a 5xx status code
func (o *GetPipelineJobStepLogsNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get pipeline job step logs not found response a status code equal to that given
func (o *GetPipelineJobStepLogsNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get pipeline job step logs not found response
func (o *GetPipelineJobStepLogsNotFound) Code() int {
	return 404
}

func (o *GetPipelineJobStepLogsNotFound) Error() string {
	return fmt.Sprintf("[GET /applications/{appName}/jobs/{jobName}/logs/{stepName}][%d] getPipelineJobStepLogsNotFound ", 404)
}

func (o *GetPipelineJobStepLogsNotFound) String() string {
	return fmt.Sprintf("[GET /applications/{appName}/jobs/{jobName}/logs/{stepName}][%d] getPipelineJobStepLogsNotFound ", 404)
}

func (o *GetPipelineJobStepLogsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
