// Code generated by go-swagger; DO NOT EDIT.

package pipeline_job

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetTektonPipelineRunTasksParams creates a new GetTektonPipelineRunTasksParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetTektonPipelineRunTasksParams() *GetTektonPipelineRunTasksParams {
	return &GetTektonPipelineRunTasksParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetTektonPipelineRunTasksParamsWithTimeout creates a new GetTektonPipelineRunTasksParams object
// with the ability to set a timeout on a request.
func NewGetTektonPipelineRunTasksParamsWithTimeout(timeout time.Duration) *GetTektonPipelineRunTasksParams {
	return &GetTektonPipelineRunTasksParams{
		timeout: timeout,
	}
}

// NewGetTektonPipelineRunTasksParamsWithContext creates a new GetTektonPipelineRunTasksParams object
// with the ability to set a context for a request.
func NewGetTektonPipelineRunTasksParamsWithContext(ctx context.Context) *GetTektonPipelineRunTasksParams {
	return &GetTektonPipelineRunTasksParams{
		Context: ctx,
	}
}

// NewGetTektonPipelineRunTasksParamsWithHTTPClient creates a new GetTektonPipelineRunTasksParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetTektonPipelineRunTasksParamsWithHTTPClient(client *http.Client) *GetTektonPipelineRunTasksParams {
	return &GetTektonPipelineRunTasksParams{
		HTTPClient: client,
	}
}

/*
GetTektonPipelineRunTasksParams contains all the parameters to send to the API endpoint

	for the get tekton pipeline run tasks operation.

	Typically these are written to a http.Request.
*/
type GetTektonPipelineRunTasksParams struct {

	/* ImpersonateGroup.

	   Works only with custom setup of cluster. Allow impersonation of test group (Required if Impersonate-User is set)
	*/
	ImpersonateGroup []string

	/* ImpersonateUser.

	   Works only with custom setup of cluster. Allow impersonation of test users (Required if Impersonate-Group is set)
	*/
	ImpersonateUser *string

	/* AppName.

	   name of Radix application
	*/
	AppName string

	/* JobName.

	   Name of pipeline job
	*/
	JobName string

	/* PipelineRunName.

	   Name of pipeline run
	*/
	PipelineRunName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get tekton pipeline run tasks params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetTektonPipelineRunTasksParams) WithDefaults() *GetTektonPipelineRunTasksParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get tekton pipeline run tasks params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetTektonPipelineRunTasksParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get tekton pipeline run tasks params
func (o *GetTektonPipelineRunTasksParams) WithTimeout(timeout time.Duration) *GetTektonPipelineRunTasksParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get tekton pipeline run tasks params
func (o *GetTektonPipelineRunTasksParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get tekton pipeline run tasks params
func (o *GetTektonPipelineRunTasksParams) WithContext(ctx context.Context) *GetTektonPipelineRunTasksParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get tekton pipeline run tasks params
func (o *GetTektonPipelineRunTasksParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get tekton pipeline run tasks params
func (o *GetTektonPipelineRunTasksParams) WithHTTPClient(client *http.Client) *GetTektonPipelineRunTasksParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get tekton pipeline run tasks params
func (o *GetTektonPipelineRunTasksParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithImpersonateGroup adds the impersonateGroup to the get tekton pipeline run tasks params
func (o *GetTektonPipelineRunTasksParams) WithImpersonateGroup(impersonateGroup []string) *GetTektonPipelineRunTasksParams {
	o.SetImpersonateGroup(impersonateGroup)
	return o
}

// SetImpersonateGroup adds the impersonateGroup to the get tekton pipeline run tasks params
func (o *GetTektonPipelineRunTasksParams) SetImpersonateGroup(impersonateGroup []string) {
	o.ImpersonateGroup = impersonateGroup
}

// WithImpersonateUser adds the impersonateUser to the get tekton pipeline run tasks params
func (o *GetTektonPipelineRunTasksParams) WithImpersonateUser(impersonateUser *string) *GetTektonPipelineRunTasksParams {
	o.SetImpersonateUser(impersonateUser)
	return o
}

// SetImpersonateUser adds the impersonateUser to the get tekton pipeline run tasks params
func (o *GetTektonPipelineRunTasksParams) SetImpersonateUser(impersonateUser *string) {
	o.ImpersonateUser = impersonateUser
}

// WithAppName adds the appName to the get tekton pipeline run tasks params
func (o *GetTektonPipelineRunTasksParams) WithAppName(appName string) *GetTektonPipelineRunTasksParams {
	o.SetAppName(appName)
	return o
}

// SetAppName adds the appName to the get tekton pipeline run tasks params
func (o *GetTektonPipelineRunTasksParams) SetAppName(appName string) {
	o.AppName = appName
}

// WithJobName adds the jobName to the get tekton pipeline run tasks params
func (o *GetTektonPipelineRunTasksParams) WithJobName(jobName string) *GetTektonPipelineRunTasksParams {
	o.SetJobName(jobName)
	return o
}

// SetJobName adds the jobName to the get tekton pipeline run tasks params
func (o *GetTektonPipelineRunTasksParams) SetJobName(jobName string) {
	o.JobName = jobName
}

// WithPipelineRunName adds the pipelineRunName to the get tekton pipeline run tasks params
func (o *GetTektonPipelineRunTasksParams) WithPipelineRunName(pipelineRunName string) *GetTektonPipelineRunTasksParams {
	o.SetPipelineRunName(pipelineRunName)
	return o
}

// SetPipelineRunName adds the pipelineRunName to the get tekton pipeline run tasks params
func (o *GetTektonPipelineRunTasksParams) SetPipelineRunName(pipelineRunName string) {
	o.PipelineRunName = pipelineRunName
}

// WriteToRequest writes these params to a swagger request
func (o *GetTektonPipelineRunTasksParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.ImpersonateGroup != nil {

		// binding items for Impersonate-Group
		joinedImpersonateGroup := o.bindParamImpersonateGroup(reg)

		// header array param Impersonate-Group
		if len(joinedImpersonateGroup) > 0 {
			if err := r.SetHeaderParam("Impersonate-Group", joinedImpersonateGroup[0]); err != nil {
				return err
			}
		}
	}

	if o.ImpersonateUser != nil {

		// header param Impersonate-User
		if err := r.SetHeaderParam("Impersonate-User", *o.ImpersonateUser); err != nil {
			return err
		}
	}

	// path param appName
	if err := r.SetPathParam("appName", o.AppName); err != nil {
		return err
	}

	// path param jobName
	if err := r.SetPathParam("jobName", o.JobName); err != nil {
		return err
	}

	// path param pipelineRunName
	if err := r.SetPathParam("pipelineRunName", o.PipelineRunName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindParamGetTektonPipelineRunTasks binds the parameter Impersonate-Group
func (o *GetTektonPipelineRunTasksParams) bindParamImpersonateGroup(formats strfmt.Registry) []string {
	impersonateGroupIR := o.ImpersonateGroup

	var impersonateGroupIC []string
	for _, impersonateGroupIIR := range impersonateGroupIR { // explode []string

		impersonateGroupIIV := impersonateGroupIIR // string as string
		impersonateGroupIC = append(impersonateGroupIC, impersonateGroupIIV)
	}

	// items.CollectionFormat: ""
	impersonateGroupIS := swag.JoinByFormat(impersonateGroupIC, "")

	return impersonateGroupIS
}
