// Code generated by go-swagger; DO NOT EDIT.

package pipeline_job

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetTektonPipelineRunTaskParams creates a new GetTektonPipelineRunTaskParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetTektonPipelineRunTaskParams() *GetTektonPipelineRunTaskParams {
	return &GetTektonPipelineRunTaskParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetTektonPipelineRunTaskParamsWithTimeout creates a new GetTektonPipelineRunTaskParams object
// with the ability to set a timeout on a request.
func NewGetTektonPipelineRunTaskParamsWithTimeout(timeout time.Duration) *GetTektonPipelineRunTaskParams {
	return &GetTektonPipelineRunTaskParams{
		timeout: timeout,
	}
}

// NewGetTektonPipelineRunTaskParamsWithContext creates a new GetTektonPipelineRunTaskParams object
// with the ability to set a context for a request.
func NewGetTektonPipelineRunTaskParamsWithContext(ctx context.Context) *GetTektonPipelineRunTaskParams {
	return &GetTektonPipelineRunTaskParams{
		Context: ctx,
	}
}

// NewGetTektonPipelineRunTaskParamsWithHTTPClient creates a new GetTektonPipelineRunTaskParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetTektonPipelineRunTaskParamsWithHTTPClient(client *http.Client) *GetTektonPipelineRunTaskParams {
	return &GetTektonPipelineRunTaskParams{
		HTTPClient: client,
	}
}

/*
GetTektonPipelineRunTaskParams contains all the parameters to send to the API endpoint

	for the get tekton pipeline run task operation.

	Typically these are written to a http.Request.
*/
type GetTektonPipelineRunTaskParams struct {

	/* ImpersonateGroup.

	   Works only with custom setup of cluster. Allow impersonation of test group (Required if Impersonate-User is set)
	*/
	ImpersonateGroup []string

	/* ImpersonateUser.

	   Works only with custom setup of cluster. Allow impersonation of test users (Required if Impersonate-Group is set)
	*/
	ImpersonateUser *string

	/* AppName.

	   name of Radix application
	*/
	AppName string

	/* JobName.

	   Name of pipeline job
	*/
	JobName string

	/* PipelineRunName.

	   Name of pipeline run
	*/
	PipelineRunName string

	/* TaskName.

	   Name of pipeline run task
	*/
	TaskName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get tekton pipeline run task params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetTektonPipelineRunTaskParams) WithDefaults() *GetTektonPipelineRunTaskParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get tekton pipeline run task params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetTektonPipelineRunTaskParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get tekton pipeline run task params
func (o *GetTektonPipelineRunTaskParams) WithTimeout(timeout time.Duration) *GetTektonPipelineRunTaskParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get tekton pipeline run task params
func (o *GetTektonPipelineRunTaskParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get tekton pipeline run task params
func (o *GetTektonPipelineRunTaskParams) WithContext(ctx context.Context) *GetTektonPipelineRunTaskParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get tekton pipeline run task params
func (o *GetTektonPipelineRunTaskParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get tekton pipeline run task params
func (o *GetTektonPipelineRunTaskParams) WithHTTPClient(client *http.Client) *GetTektonPipelineRunTaskParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get tekton pipeline run task params
func (o *GetTektonPipelineRunTaskParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithImpersonateGroup adds the impersonateGroup to the get tekton pipeline run task params
func (o *GetTektonPipelineRunTaskParams) WithImpersonateGroup(impersonateGroup []string) *GetTektonPipelineRunTaskParams {
	o.SetImpersonateGroup(impersonateGroup)
	return o
}

// SetImpersonateGroup adds the impersonateGroup to the get tekton pipeline run task params
func (o *GetTektonPipelineRunTaskParams) SetImpersonateGroup(impersonateGroup []string) {
	o.ImpersonateGroup = impersonateGroup
}

// WithImpersonateUser adds the impersonateUser to the get tekton pipeline run task params
func (o *GetTektonPipelineRunTaskParams) WithImpersonateUser(impersonateUser *string) *GetTektonPipelineRunTaskParams {
	o.SetImpersonateUser(impersonateUser)
	return o
}

// SetImpersonateUser adds the impersonateUser to the get tekton pipeline run task params
func (o *GetTektonPipelineRunTaskParams) SetImpersonateUser(impersonateUser *string) {
	o.ImpersonateUser = impersonateUser
}

// WithAppName adds the appName to the get tekton pipeline run task params
func (o *GetTektonPipelineRunTaskParams) WithAppName(appName string) *GetTektonPipelineRunTaskParams {
	o.SetAppName(appName)
	return o
}

// SetAppName adds the appName to the get tekton pipeline run task params
func (o *GetTektonPipelineRunTaskParams) SetAppName(appName string) {
	o.AppName = appName
}

// WithJobName adds the jobName to the get tekton pipeline run task params
func (o *GetTektonPipelineRunTaskParams) WithJobName(jobName string) *GetTektonPipelineRunTaskParams {
	o.SetJobName(jobName)
	return o
}

// SetJobName adds the jobName to the get tekton pipeline run task params
func (o *GetTektonPipelineRunTaskParams) SetJobName(jobName string) {
	o.JobName = jobName
}

// WithPipelineRunName adds the pipelineRunName to the get tekton pipeline run task params
func (o *GetTektonPipelineRunTaskParams) WithPipelineRunName(pipelineRunName string) *GetTektonPipelineRunTaskParams {
	o.SetPipelineRunName(pipelineRunName)
	return o
}

// SetPipelineRunName adds the pipelineRunName to the get tekton pipeline run task params
func (o *GetTektonPipelineRunTaskParams) SetPipelineRunName(pipelineRunName string) {
	o.PipelineRunName = pipelineRunName
}

// WithTaskName adds the taskName to the get tekton pipeline run task params
func (o *GetTektonPipelineRunTaskParams) WithTaskName(taskName string) *GetTektonPipelineRunTaskParams {
	o.SetTaskName(taskName)
	return o
}

// SetTaskName adds the taskName to the get tekton pipeline run task params
func (o *GetTektonPipelineRunTaskParams) SetTaskName(taskName string) {
	o.TaskName = taskName
}

// WriteToRequest writes these params to a swagger request
func (o *GetTektonPipelineRunTaskParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.ImpersonateGroup != nil {

		// binding items for Impersonate-Group
		joinedImpersonateGroup := o.bindParamImpersonateGroup(reg)

		// header array param Impersonate-Group
		if len(joinedImpersonateGroup) > 0 {
			if err := r.SetHeaderParam("Impersonate-Group", joinedImpersonateGroup[0]); err != nil {
				return err
			}
		}
	}

	if o.ImpersonateUser != nil {

		// header param Impersonate-User
		if err := r.SetHeaderParam("Impersonate-User", *o.ImpersonateUser); err != nil {
			return err
		}
	}

	// path param appName
	if err := r.SetPathParam("appName", o.AppName); err != nil {
		return err
	}

	// path param jobName
	if err := r.SetPathParam("jobName", o.JobName); err != nil {
		return err
	}

	// path param pipelineRunName
	if err := r.SetPathParam("pipelineRunName", o.PipelineRunName); err != nil {
		return err
	}

	// path param taskName
	if err := r.SetPathParam("taskName", o.TaskName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindParamGetTektonPipelineRunTask binds the parameter Impersonate-Group
func (o *GetTektonPipelineRunTaskParams) bindParamImpersonateGroup(formats strfmt.Registry) []string {
	impersonateGroupIR := o.ImpersonateGroup

	var impersonateGroupIC []string
	for _, impersonateGroupIIR := range impersonateGroupIR { // explode []string

		impersonateGroupIIV := impersonateGroupIIR // string as string
		impersonateGroupIC = append(impersonateGroupIC, impersonateGroupIIV)
	}

	// items.CollectionFormat: ""
	impersonateGroupIS := swag.JoinByFormat(impersonateGroupIC, "")

	return impersonateGroupIS
}
