// Code generated by go-swagger; DO NOT EDIT.

package application

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/equinor/radix-cli/generated-client/models"
)

// GetResourcesReader is a Reader for the GetResources structure.
type GetResourcesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetResourcesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetResourcesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewGetResourcesNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /applications/{appName}/resources] getResources", response, response.Code())
	}
}

// NewGetResourcesOK creates a GetResourcesOK with default headers values
func NewGetResourcesOK() *GetResourcesOK {
	return &GetResourcesOK{}
}

/*
GetResourcesOK describes a response with status code 200, with default header values.

Successful trigger pipeline
*/
type GetResourcesOK struct {
	Payload *models.UsedResources
}

// IsSuccess returns true when this get resources o k response has a 2xx status code
func (o *GetResourcesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get resources o k response has a 3xx status code
func (o *GetResourcesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get resources o k response has a 4xx status code
func (o *GetResourcesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get resources o k response has a 5xx status code
func (o *GetResourcesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get resources o k response a status code equal to that given
func (o *GetResourcesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get resources o k response
func (o *GetResourcesOK) Code() int {
	return 200
}

func (o *GetResourcesOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /applications/{appName}/resources][%d] getResourcesOK %s", 200, payload)
}

func (o *GetResourcesOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /applications/{appName}/resources][%d] getResourcesOK %s", 200, payload)
}

func (o *GetResourcesOK) GetPayload() *models.UsedResources {
	return o.Payload
}

func (o *GetResourcesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UsedResources)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetResourcesNotFound creates a GetResourcesNotFound with default headers values
func NewGetResourcesNotFound() *GetResourcesNotFound {
	return &GetResourcesNotFound{}
}

/*
GetResourcesNotFound describes a response with status code 404, with default header values.

Not found
*/
type GetResourcesNotFound struct {
}

// IsSuccess returns true when this get resources not found response has a 2xx status code
func (o *GetResourcesNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get resources not found response has a 3xx status code
func (o *GetResourcesNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get resources not found response has a 4xx status code
func (o *GetResourcesNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get resources not found response has a 5xx status code
func (o *GetResourcesNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get resources not found response a status code equal to that given
func (o *GetResourcesNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get resources not found response
func (o *GetResourcesNotFound) Code() int {
	return 404
}

func (o *GetResourcesNotFound) Error() string {
	return fmt.Sprintf("[GET /applications/{appName}/resources][%d] getResourcesNotFound", 404)
}

func (o *GetResourcesNotFound) String() string {
	return fmt.Sprintf("[GET /applications/{appName}/resources][%d] getResourcesNotFound", 404)
}

func (o *GetResourcesNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
