// Code generated by go-swagger; DO NOT EDIT.

package application

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// ResetManuallyScaledComponentsInApplicationReader is a Reader for the ResetManuallyScaledComponentsInApplication structure.
type ResetManuallyScaledComponentsInApplicationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ResetManuallyScaledComponentsInApplicationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewResetManuallyScaledComponentsInApplicationOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewResetManuallyScaledComponentsInApplicationUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewResetManuallyScaledComponentsInApplicationNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /applications/{appName}/reset-scale] resetManuallyScaledComponentsInApplication", response, response.Code())
	}
}

// NewResetManuallyScaledComponentsInApplicationOK creates a ResetManuallyScaledComponentsInApplicationOK with default headers values
func NewResetManuallyScaledComponentsInApplicationOK() *ResetManuallyScaledComponentsInApplicationOK {
	return &ResetManuallyScaledComponentsInApplicationOK{}
}

/*
ResetManuallyScaledComponentsInApplicationOK describes a response with status code 200, with default header values.

Application started ok
*/
type ResetManuallyScaledComponentsInApplicationOK struct {
}

// IsSuccess returns true when this reset manually scaled components in application o k response has a 2xx status code
func (o *ResetManuallyScaledComponentsInApplicationOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this reset manually scaled components in application o k response has a 3xx status code
func (o *ResetManuallyScaledComponentsInApplicationOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this reset manually scaled components in application o k response has a 4xx status code
func (o *ResetManuallyScaledComponentsInApplicationOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this reset manually scaled components in application o k response has a 5xx status code
func (o *ResetManuallyScaledComponentsInApplicationOK) IsServerError() bool {
	return false
}

// IsCode returns true when this reset manually scaled components in application o k response a status code equal to that given
func (o *ResetManuallyScaledComponentsInApplicationOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the reset manually scaled components in application o k response
func (o *ResetManuallyScaledComponentsInApplicationOK) Code() int {
	return 200
}

func (o *ResetManuallyScaledComponentsInApplicationOK) Error() string {
	return fmt.Sprintf("[POST /applications/{appName}/reset-scale][%d] resetManuallyScaledComponentsInApplicationOK", 200)
}

func (o *ResetManuallyScaledComponentsInApplicationOK) String() string {
	return fmt.Sprintf("[POST /applications/{appName}/reset-scale][%d] resetManuallyScaledComponentsInApplicationOK", 200)
}

func (o *ResetManuallyScaledComponentsInApplicationOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewResetManuallyScaledComponentsInApplicationUnauthorized creates a ResetManuallyScaledComponentsInApplicationUnauthorized with default headers values
func NewResetManuallyScaledComponentsInApplicationUnauthorized() *ResetManuallyScaledComponentsInApplicationUnauthorized {
	return &ResetManuallyScaledComponentsInApplicationUnauthorized{}
}

/*
ResetManuallyScaledComponentsInApplicationUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type ResetManuallyScaledComponentsInApplicationUnauthorized struct {
}

// IsSuccess returns true when this reset manually scaled components in application unauthorized response has a 2xx status code
func (o *ResetManuallyScaledComponentsInApplicationUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this reset manually scaled components in application unauthorized response has a 3xx status code
func (o *ResetManuallyScaledComponentsInApplicationUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this reset manually scaled components in application unauthorized response has a 4xx status code
func (o *ResetManuallyScaledComponentsInApplicationUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this reset manually scaled components in application unauthorized response has a 5xx status code
func (o *ResetManuallyScaledComponentsInApplicationUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this reset manually scaled components in application unauthorized response a status code equal to that given
func (o *ResetManuallyScaledComponentsInApplicationUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the reset manually scaled components in application unauthorized response
func (o *ResetManuallyScaledComponentsInApplicationUnauthorized) Code() int {
	return 401
}

func (o *ResetManuallyScaledComponentsInApplicationUnauthorized) Error() string {
	return fmt.Sprintf("[POST /applications/{appName}/reset-scale][%d] resetManuallyScaledComponentsInApplicationUnauthorized", 401)
}

func (o *ResetManuallyScaledComponentsInApplicationUnauthorized) String() string {
	return fmt.Sprintf("[POST /applications/{appName}/reset-scale][%d] resetManuallyScaledComponentsInApplicationUnauthorized", 401)
}

func (o *ResetManuallyScaledComponentsInApplicationUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewResetManuallyScaledComponentsInApplicationNotFound creates a ResetManuallyScaledComponentsInApplicationNotFound with default headers values
func NewResetManuallyScaledComponentsInApplicationNotFound() *ResetManuallyScaledComponentsInApplicationNotFound {
	return &ResetManuallyScaledComponentsInApplicationNotFound{}
}

/*
ResetManuallyScaledComponentsInApplicationNotFound describes a response with status code 404, with default header values.

Not found
*/
type ResetManuallyScaledComponentsInApplicationNotFound struct {
}

// IsSuccess returns true when this reset manually scaled components in application not found response has a 2xx status code
func (o *ResetManuallyScaledComponentsInApplicationNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this reset manually scaled components in application not found response has a 3xx status code
func (o *ResetManuallyScaledComponentsInApplicationNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this reset manually scaled components in application not found response has a 4xx status code
func (o *ResetManuallyScaledComponentsInApplicationNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this reset manually scaled components in application not found response has a 5xx status code
func (o *ResetManuallyScaledComponentsInApplicationNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this reset manually scaled components in application not found response a status code equal to that given
func (o *ResetManuallyScaledComponentsInApplicationNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the reset manually scaled components in application not found response
func (o *ResetManuallyScaledComponentsInApplicationNotFound) Code() int {
	return 404
}

func (o *ResetManuallyScaledComponentsInApplicationNotFound) Error() string {
	return fmt.Sprintf("[POST /applications/{appName}/reset-scale][%d] resetManuallyScaledComponentsInApplicationNotFound", 404)
}

func (o *ResetManuallyScaledComponentsInApplicationNotFound) String() string {
	return fmt.Sprintf("[POST /applications/{appName}/reset-scale][%d] resetManuallyScaledComponentsInApplicationNotFound", 404)
}

func (o *ResetManuallyScaledComponentsInApplicationNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
