name: Create releases and tags
on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions: {}
jobs:
  unreleased-prs-metadata:
    name: Get list of pending release pull requests
    permissions:
      pull-requests: read
      contents: read
    uses: equinor/radix-reusable-workflows/.github/workflows/template-unreleased-pr-metadata.yml@c09456726181391559941adde1a467846eb60975 # v1.2.0

  release-pull-request:
    name: Release pull request
    needs:
      - unreleased-prs-metadata
    if: needs.unreleased-prs-metadata.outputs.unreleased-pull-request-count > 0
    strategy:
      matrix:
        pull-request-number: ${{ fromJson(needs.unreleased-prs-metadata.outputs.unreleased-pull-requests) }}
    permissions:
      pull-requests: write
      contents: read
      issues: write
    uses: equinor/radix-reusable-workflows/.github/workflows/template-create-release-from-pr.yml@c09456726181391559941adde1a467846eb60975 # v1.2.0
    with:
      pull-request-number: ${{ matrix.pull-request-number }}
      use-github-app-token: true
      github-app-id: ${{ vars.GH_APP_ID }}
      set-draft: true
    secrets:
      github-app-private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}

  tag:
    needs:
      - release-pull-request
      - unreleased-prs-metadata
    if: needs.unreleased-prs-metadata.outputs.unreleased-pull-request-count == 1
    runs-on: radix-runner
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Configure Git with Context

        run: |
          tag="${{ needs.release-pull-request.outputs.tag }}"
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
          git tag -a "$tag" -m "Tag created by ${{ github.actor }}"
          git push origin "$tag"
