name: Prepare release pull request
on:
  push: 
    tags:
      - '**'
    branches: 
      - master
  workflow_dispatch:

permissions: {}
concurrency:
  group: ${{ github.workflow }}

jobs:
  prepare-release-pr:
    name: Prepare release pull request
    uses: equinor/radix-reusable-workflows/.github/workflows/template-prepare-release-pr.yml@bbbf79dd34776ca9e9a4dc4fcf6dc643953f37e8 # v1.1.0
    permissions:
      contents: write
      pull-requests: write
      issues: write
    with:
      branch: master
      cliff-config-path: cliff.toml
      generate-pre-release-pr: false
