name: Prepare release pull request
on:
  push:
    tags:
      - "**"
    branches:
      - master
  workflow_dispatch:

permissions: {}
concurrency:
  group: ${{ github.workflow }}

jobs:
  prepare-release-pr:
    name: Prepare release pull request
    uses: equinor/radix-reusable-workflows/.github/workflows/template-prepare-release-pr.yml@c09456726181391559941adde1a467846eb60975 # v1.2.0
    permissions:
      contents: write
      pull-requests: write
      issues: write
    with:
      branch: master
      cliff-config-path: cliff.toml
      generate-pre-release-pr: false
